[package]
name = "chip8"
description = "A CHIP-8 emulator written in Rust"
version = "1.0.2"
license = "MIT"
keywords = ["chip8"]

[[bin]]
name = "chip8"
path = "src/main.rs"

[dependencies]
sdl2 = "0.9.1"
rand = "0.3.11"
time = "0.1.32"
